services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=login_social_db
    restart: 'always'
    # Deve aguardar o banco ficar operacional
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend-login-social
    container_name: backend
    ports:
      - 3001:3001
      - 9229:9229
    command: dev
    volumes:
      - ./backend-login-social:/app-backend
    environment:
      - API_PORT=3001
      - JWT_SECRET=senhajwt
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
      - DATABASE=login_social_db
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend-login-social
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - FRONT_PORT=3000
      - VITE_BASE_URL=http://localhost:3001
    volumes:
      - ./frontend-login-social:/app-frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5