FROM node:20-alpine as builder

WORKDIR /app-frontend

COPY package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build

FROM nginx:stable-alpine-slim as production

WORKDIR /usr/share/nginx/html

COPY --from=builder ./app-frontend/dist .

EXPOSE 80